[package]
name = "focus"
version = "0.1.0"
authors = ["Marcos C. F. <markcfleury@gmail.com>"]

[dependencies]
time = "0.1"
rand = "0.3"
ordered-float = "0.5.0"
nix = "0.9.0"
conrod = { version = "^0.57.0", features = ["winit", "glium"] }
find_folder = "0.1"
scrap = "0.5.0"
os_type="1.0.0"
